### ISSUE TITLE
Basic queries and log folder

### ISSUE THREAD

**Issue by vlkator** [fjxmlzn/FindMyHistory#4]
Sorry for the amateur question. I am a beginner in apple world and also terminal and macbook. I understand that the terminal is similar to commander in windows, but I don't understand the connections exactly yet. Like github, it is unknown to me.

I downloaded the zip file, allowed terminal access to the folders and ran the code using the code. The script obviously logs all my devices, shows how many updates there have been and the update time. So everything works. But I have a few basic questions and would like an amateur and simple explanation.

1. I always have to run the script using that complicated code in the terminal. Is it not possible for main.py to function as an exe file simply to run?
2. How to terminate the program? Just close the terminal, everything is always saved?
3. Absolutely basic question. The help says that everything is saved in the "log" folder in the CVS file. But where should I look for this folder??? It's nowhere. I've looked everywhere, but the folder with the logo doesn't exist. It was not created even after closing the terminal.
4. When the position saving script is running, where should I write --help if it is not possible to write in that window and the next terminal window cannot be started?

I really apologize for the amateurism.

**Comment by vlkator** [comment]
I found a good folder. Along with the logos. I can import the points into google earth, but there is one small error. Individual points do not have time stamps. It would require that individual points have information about the time when they were saved.

**Comment by fjxmlzn** [comment]
Glad to hear that you found the folder. The CSV files contain the timestamps. Could you please paste a screenshot of the error you saw on Google earth?

**Comment by fjxmlzn** [comment]
Close the issue for now. Feel free to reopen it if you still experience issues.

**Comment by OlDirty89** [comment]
@fjxmlzn I don't understand the location|timeStamp.
It says `1690396140000` in the CSV log.
Anything wrong here?
Time format in Terminal looks just fine.
<img width="176" alt="image" src="https://github.com/fjxmlzn/FindMyHistory/assets/37001776/637b0332-6466-43ef-8512-799433125fb0">

**Comment by fjxmlzn** [comment]
@OlDirty89 It is unix timestamp https://en.wikipedia.org/wiki/Unix_time
