### ISSUE TITLE
How to access the cache data

### ISSUE THREAD

**Issue by cherubzhenhu** [fjxmlzn/FindMyHistory#6]
I follow the steps sign-in on Mac (https://support.apple.com/en-us/HT204053). And connect my ipad with Mac by USB. Also allow full disk access from your instruction.

However, I can find the cache file in /Library/Caches/com.apple.findmy.fmipcore/Items.data

Need your help.

**Comment by fjxmlzn** [comment]
Do you mean you *cannot* find the cache file in /Library/Caches/com.apple.findmy.fmipcore/Items.data?

Did you open the findmy app on your Mac?

**Comment by fjxmlzn** [comment]
Close the issue for now. Feel free to reopen it if you still experience issues.
