### ISSUE TITLE
Help command-line option doesn't work

### ISSUE THREAD

**Issue by jtara** [fjxmlzn/FindMyHistory#9]
Using the -h or --help option produces no output, displays "keyboard interrupt".

MacOS Ventura 13.0.1, 2020 iMac 27"

Possibly could be related to my use of Karabiner-Elements? (Keyboard remapper)

https://karabiner-elements.pqrs.org/

I was able to successfully use the --no_date_folder option. 

Wanted to look at the exact usage of file naming option. No biggie, will look at source code...

**Comment by fjxmlzn** [comment]
It is a bug and is fixed now. Thanks for catching that!
